services:
  api:
    image: kirixo/libum_api:1.0.0
    volumes:
      - ./backend:/app
      - ./backend/dockerbuild:/build
    networks:
      - app-network

  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - NODE_ENV=development
    command: sh -c "chmod -R 777 node_modules/ dist/ && npm install && npm run build"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/dist:/usr/share/nginx/html
    depends_on:
      - api
      - frontend
    networks:
      - app-network

networks:
  app-network: